### ISSUE TITLE
Create/edit/disable pharmacy

### ISSUE THREAD

**Issue by mverzilli** [instedd/maap-collector#11]
(In the Electron app)

Fields:

1. Name (string; required).
2. Date of visit (date; required; defaults to today).
3. Registration number and body under which it is registered. (string; optional)
4. Address (string; optional).
5. GPS location (lat/lng; optional).
6. Location setting (urban | peri-urban | rural; optional).
7. Ownership type (public | private | faith based | community | other (specify)).
8. Contact details: name (string), designation (string), email (string), mobile (string).
9. Manual records keeping (bool).
10. Electronic records keeping (bool).
11. Available record types (select many: sales invoices to customers | prescriptions | purchase records from supplier | other (specify)).
12. Surrounding community pharmacies: pick from list or create on the fly with name, address and type "community".

**Comment by hdf1986** [comment]
@mverzilli is this going to be on the backoffice or the electron app?

**Comment by mverzilli** [comment]
Clarified!

**Comment by mverzilli** [comment]
duplicate
