### ISSUE TITLE
Enter transaction level sales data for pharmacy

### ISSUE THREAD

**Issue by mverzilli** [instedd/maap-collector#12]
Fields:

Date of sale: date (required)
Volume (number of packs): number (required)
Sales price per pack: number (optional?)
In-patient or out-patient?: bool (optional)
Department/ward: string (optional)
Dispensed against prescription/note: bool (optional)

**Comment by pmallol** [comment]
@mverzilli is this transaction aggregated? Or should the user be able to add a record for each unique transaction?

**Comment by mverzilli** [comment]
This is individual (note that a single transaction may include many packs of the same thing, though).

**Comment by mverzilli** [comment]
Out of scope
