### ISSUE TITLE
UI shows same patient twice

### ISSUE THREAD

**Issue by mmuller** [instedd/maap-collector#125]
Steps to reproduce:
Create a patient with `Patient ID 1` from the `Device A`.
Create a patient with `Patient ID 1` from the `Device B`.
Observe the patients listing.

Obtained:
The `Device B` includes the same patient twice.

![image](https://user-images.githubusercontent.com/518152/63694225-52fc8180-c7ec-11e9-8cc0-34d947982fe0.png)

![image](https://user-images.githubusercontent.com/518152/63694236-5a238f80-c7ec-11e9-9d09-d96347510680.png)

![image](https://user-images.githubusercontent.com/518152/63694265-6ad40580-c7ec-11e9-9733-40de3ac34ddd.png)

**Comment by mverzilli** [comment]
Can you check if this still happens at `0.17.5-dev`?

**Comment by mmuller** [comment]
Working properly
