### ISSUE TITLE
Patients cannot be edited by other devices except the originator 

### ISSUE THREAD

**Issue by mmuller** [instedd/maap-collector#140]
**Steps to reproduce:**

1. Create a `Patient Foo` from the `Device A`.
2. Edit the `Patient Foo`'s Gender from the `Device B`.
3. Observe the `Patient Foo`'s Gender shown in the `Device A`.   
4. Observe the `Patient Foo`'s Gender shown in the `Store`.   

**Obtained:**

- The modification is only displayed in the `Device B`.

**Comment by mverzilli** [comment]
Would you check on `0.17.5-dev`?
