### ISSUE TITLE
Patients entries cannot be edited

### ISSUE THREAD

**Issue by mmuller** [instedd/maap-collector#142]
**Steps to reproduce:**

1. Create a `Patient Foo` from the `Device A`.
2. Add an entry `E` to the `Patient Foo`.
3. Edit the entry `E`.
4. Observe the entry `E` in the `Store`.   

**Obtained:**

- The modification is not displayed in the `Store`.
- The modification is not displayed in other Devices.
- The modification is only displayed in the `Device A`.

**Comment by mverzilli** [comment]
Can you check if this still is reproducible in version `0.17.5-dev`? I think it should work correctly there.
