### ISSUE TITLE
Add new fields to server side site editor

### ISSUE THREAD

**Issue by mverzilli** [instedd/maap-collector#183]

**Comment by manumoreira** [comment]
https://docs.google.com/spreadsheets/d/10j6t8dBkPritA8nBpFXaDghWDm9kjarueku0t3YXzVA/edit?usp=sharing

**Comment by mverzilli** [comment]
Solved via: https://github.com/instedd/maap-store/pull/44

**Comment by mmuller** [comment]
Working properly in version 0.17.7-dev
