### ISSUE TITLE
Enter dispensing records

### ISSUE THREAD

**Issue by mverzilli** [instedd/maap-collector#19]
Scenario 1: Electronic records (electronic dispensing/ issues data) are maintained in the facility 
Scenario 1.1: If transaction level data is available: 
For each of the antibiotic pack-description that appears in the drop-down menu of the tool, please complete the following information for all transactions of antibiotics issued during 2018: 
•	Date of issue to facility type 1 (Specify ‘type of facility’ as well) 
•	Volume (number of packs) issued 
•	Value of antibiotics issued 
•	Repeat above entries for each transaction to each facility type (type 2, 3 and so one)

Scenario 1.2:  If transaction level sales data is not available, i.e. only aggregated data available: 
For each of the antibiotic pack-description that appears in the drop-down menu of the tool, please complete the following information for each month from January to December 2018: 
•	Opening stock of antibiotic (number of packs) on first day of January 2018 
•	Each entry of issues-in of antibiotics (number of packs) during January 2018 
•	Each entry of issues-out of antibiotics (number of packs) during January 2018
•	Closing stock of antibiotics (number of packs) on last day of January 2018 
•	Repeat above entries for each month till December 2018 

Scenario 2: Manual records (or bin card entry system) are maintained in the facility 
For each of the antibiotic pack-description that appears in the drop-down menu of the tool, please complete the following information for each month from January to December 2018: 
•	Opening stock of antibiotic (number of packs) in January 2018 
•	Each entry of issues-in of antibiotics (number of packs) in January 2018 
•	Each entry of issues-out of antibiotics (number of packs) in January 2018
•	Closing stock of antibiotics (number of packs) in January 2018 
Repeat above entries for each month till December 2018

**Comment by pyritewolf** [comment]
We should probably break up this leviathan in smaller issues.

**Comment by mverzilli** [comment]
Sounds good, working on it :)

**Comment by mverzilli** [comment]
Superceded by #23, #24 and #25.
