### ISSUE TITLE
endless sync when leaving app opened while device sleep

### ISSUE THREAD

**Issue by manumoreira** [instedd/maap-collector#205]
If the user leaves the app opened while the device sleeps then the synchronizing message stays endless, and data does not get synchronized.

**Comment by lmatayoshi** [comment]
A condition of endless syncing can be reached by following these steps:

1) Move from tab "Lab Records" to "Patient records". (Or to any other tab). A `sync` event will be triggered
2) While the app syncs, get into `offline mode`. For example, by turning off the Wi-Fi
3) Even if you turn on the Wi-Fi again, the sync process will never finish

I have been checking the events, and what is happening is that a `net::ERR_INTERNET_DISCONNECTED` is being triggered followed by an 
`Uncaught (in promise) TypeError: Failed to fetch `. That causes the `syncing` process never end properly. Therefore `synchronizing` field  in redux store remains in `true` and will never be set to `false`
