### ISSUE TITLE
Rename and add dropdown in Recipient facility column at stock movement form (show drop-down only for 'Issued Out')

### ISSUE THREAD

**Issue by hdf1986** [instedd/maap-collector#226]
"The Recipient Facility column needs to be renamed to `Sold/dispensed to` and should have the following options for a dropdown
1)For in-patients
2)For out-patients
3)For outside hospital

If issued IN this fields will be grey out"

**Comment by manumoreira** [comment]
This was requested by Dr Sangam during the Eswatini trip on October 24th. 
It goes against the request made by (Jess) CDDEP in the previous trip to Eswatini on July 10th
