### ISSUE TITLE
Rename and add dropdown in Recipient Unit column at stock movement

### ISSUE THREAD

**Issue by hdf1986** [instedd/maap-collector#227]
"The Recipient Unit column need to be rename to Departments (it will be enabled only if option 1 (For in-patients) is selected at 'Sold/dispensed to'. 
The options are
1)        Medicine ward
2)        Surgery ward
3)        Obstetrics / maternity ward
4)        Gynaecology ward
5)        Paediatrics & Neonatology ward
6)        Pulmonology ward
7)        Orthopaedics ward
8)        Geriatrics ward
9)       Nephrology ward
10)       ENT ward
11) Others"

**Comment by manumoreira** [comment]
This was requested by Dr Sangam during the Eswatini trip on October 24th. 
It goes against the request made by (Jess) CDDEP in the previous trip to Eswatini on July 10th
