### ISSUE TITLE
Toogle button to disable encryption/hashing/editing options in lab records

### ISSUE THREAD

**Issue by manumoreira** [instedd/maap-collector#270]
The most complex functions in lab records are around hashing, encrypting and allowing to manually edit patient records from the collector. None of this is being used now and based on the agreements in the MAAP project it will not be used in the future.

We can rely on the `is_hospital` property of a site to enable/disable all these features and enhance the performance.

**Comment by lmatayoshi** [comment]
Watch out! 
At this moment: When an import of a non-hospital is uploaded, it remains obfuscating forever in the server
