### ISSUE TITLE
[Admin] Remove `n+1`, unnecesary filters and properties from ActiveAdmin tabs

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/maap-collector#277]
Examples of this include: 
- `:antibiotics` and `:site` in AntibioticConsumptionStats tab (N+1)
- Sheet file attachment, Sheet file blob and Lab Records filters in Lab Records Import tab

**Comment by lmatayoshi** [comment]
Removed filters by screen: (I took advantage of making filters explicit to remove `Header row`, `Data rows from`, `Data rows to`, `Raw error message` filters. Not because of performance issues but because IMHO they introduce a weird criteria and screen clutter)

Electronic Pharmacy Stock Records:
- Sheet file attachment
- Sheet file blob
- Header row
- Data rows from
- Data rows to
- Raw error message

Lab Record Imports:
- Sheet file attachment
- Sheet file blob
- Lab records
- Header row
- Data rows from
- Data rows to
- Patient ID state
- Raw error message

Sites:
- Patient ID Hashes (Unintelligible Ruby Objects)
- Patients (Unintelligible Ruby Objects)

**Comment by lmatayoshi** [comment]
QA: The most practical way of testing this is checking that every entity is properly listed after navigating to its proper tab and that the remaining filters for each entity works

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/maap-store/commit/4df2f66d88c81260962063a9201928409802c5a3
