### ISSUE TITLE
Hide features for non-hospital sites

### ISSUE THREAD

**Issue by pyritewolf** [instedd/maap-collector#283]
Some features should not be visible outside of hospital sites:

- [x] LabRecord editing
- [x] PatientID/Date/PHI selection on imports
- [x] ID review on imports
- [x] Patient records listing

**Comment by manumoreira** [comment]
For non-hospital sites the UI behaves OK, hiding options (PatientRecords, All obfuscation options in LabRecord wizard) but the files uploaded keep obfuscating endlessly at the store
