### ISSUE TITLE
Filenames for downloadable labRecordImports and ElectronicPharmacyRecords format

### ISSUE THREAD

**Issue by manumoreira** [instedd/maap-collector#296]
Filenames for downloadable labRecordImports and ElectronicPharmacyRecords should be fileId-originalFileName-siteId.<originalextension>

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/maap-store/commit/8b1ad1752a04ccbc8fef462aec12fb7e43dc87c0
