### ISSUE TITLE
Add constraint for deleting attachments when deleting labrecordimports

### ISSUE THREAD

**Issue by pyritewolf** [instedd/maap-collector#297]

**Comment by lmatayoshi** [comment]
I decided not to move forward with this issue, after commenting it with @pyritewolf 

At this moment, when executing `someInstance.destroy`, rows belonging to `active_storage_attachments` and `active_storage_blobs` associated with that instance will be deleted along with the attachment. This functionality is provided by macro `has_one_attached`.
This means that we can always count on `destroy` function to reliably delete a LabRecordImport or ElectronicPharmacyStockRecord along with their attachments.

This issue points out the potential inconsistent end state when manually deleting a record associated with an attachment, which isn't solved yet. However, even though Constraints, `ON DELETE` clauses, `Triggers` or other SQL artifacts could work, they can be tough to implement and could potentially clash with ActiveStorage implementation. For example, the latter provides a `purge_later` functionality which can be difficult to keep at database level.

Best trade-off we found is avoid deleting LabRecordImports or ElectronicPharmacyStockRecords other than using the `destroy` method and add this decision to the docs.
