### ISSUE TITLE
Duplicated imports in store

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/maap-collector#310]
This is a Legacy issue. It's been happening since a couple of months ago, and different Collectors have reported the same issue.

Sometimes, after performing a `LabRecordImport`, file ends up being imported twice server side. Check if the problem is in the Collector side (if the request is being sent twice), or if it's in the store (a single request is being received but it's being processed twice).

Checking `Network` pane can help to check if the problem is in the Collector side

**Comment by manumoreira** [comment]
We've learnt that this is caused by duplicated requests in the collector. Apparently this is only caused by forcing sync (e.g.switching tabs) while the request is still pending (files > ~ 1MB take more than 10 sec to finish the request.)
To reproduce the error:
1. Upload a lab file > 2 MB
2. Complete the wizard process
3. Once it's finished go back quickly to the lab records list (this should force 1 new sync) 
4. Switch tabs (this should force a second sync)
The result should be 3 requests on the collector and 3 files uploaded to the store

**Comment by manumoreira** [comment]
Prevent sync when request or sync pending or ongoing

**Comment by lmatayoshi** [comment]
@mmuller , this should be tested with new version `1.1.1-demo` (Windows and Mac).
As usual, main thing to test here is checking that synchronization still works as usual. 
**But**, there are some key points.

If you pay attention in previous versions of Collector, you'll see that syncing process finishes
in a short period of time. No matter if you've uploaded a lot of heavy files, that 
doesn't affect the duration of the syncing. The spinner will spin for a short period of time,
and after that, Collector will inform that syncing process is completed.
That is because until now, syncing process wasn't waiting for server's responses to finish.
It just triggered the requests without waiting for the replies.

Having said that, things to test here are:
1. Check that new entities coming from the server are correctly _FETCHED_ during the syncing
process. For example, create some new antibiotics in the admin store. After syncing,
those new antibiotics should be available in the Collector. Antibiotics
can be created using the "New Antibiotic" button in Admin's UI. 
2. Check that new standard entities created in the Collector are correctly _UPLOADED_ to the server during the syncing process. With "standard entities" I'm referring to those that doesn't require an import process to be uploaded: New Patients, Antibiotics or AntibioticConsumptionStats.
You can test this with one, two, or the three of them.
3. Check that standard entities updated in the Collector are correctly _UPDATED_ in the server.
Again, test this with a subset of Patients, Antibiotics, AntibioticConsumptionStats
4. Check that LabRecordImports created and updated from the Collector are correctly _UPLOADED_
and _UPDATED_ in the server. Updating a LRI means accessing its details and changing the
ID of one or more patients (That option is only available for Sites that has a Hospital).
LRImports from other Collectors aren't fetched from the server, so nothing to check regarding fetching.
5. Check that ElectronicPharmacyStockRecords created from the Collector (ElectonicPH doesn't
suport neither fetching nor updating action) are correctly _UPLOADED_ to the server.
ElectronicPHImports from other Collectors aren't fetched from the server, so nothing to check regarding fetching.
6. When testing (4) and (5), try uploading heavy files such as `SANDOF` and start switching between tabs. At the end of the process, no duplicates should have been generated server side.

In all cases, sync process should last until all the entities have completed its sync.
That can take considerable time. For example, if heavy LabRecordImports are being uploaded
to the server. Triggering a new sync process by switching between tabs shouldn't trigger any
new request to the server unless the previous process has finished. You can check that using
the network tab in Collector's Dev Tools.
