### ISSUE TITLE
Lab page

### ISSUE THREAD

**Issue by mverzilli** [instedd/maap-collector#7]
(Data collector app)

A lab has:

+ Name: string
+ Address: string
+ Location: lat/lng
+ Ownership: public | private
+ InFacility: bool
+ HasPharmacy: bool

+ ClinicalServices: many of ClinicalServices | other(specify)

+ IdentifiedPatients: bool
If identified patients, let the user specify:
+PatientIdentificationSystemChangedSince2018: bool (null by default)
+PatientIdentificationSystemChanges: string (null by default)

+ PermanentlyIdentifiedPatients: bool
+ HasMicrobiologist: bool
+ HasTechnician: bool
+ TestedSpecimenTypes: specimentype | string
+ RequestForms: many of paper | electronic |
other (string)

+ HasInfoAboutSpecimens: bool
If yes, specify:
+ AverageNumberOfSpecimensProcessedForBacterialCulturesPerYear: number
+ AverageNumberOfSpecimensWithBacterialGrowthProcessedForSusceptibility: number

ClinicalServices: medical, surgical, pediatric, maternity and gynecological, not mentioned

From this place we should also be able to the record list, create new record manually and/or import bulk lab records

Just for additional context, we might add the list below as custom fields, but let's wait until we're sure we'll need them before adding them:

+ AMRNationalSurveillanceSite: bool
+ WHOGlassReporter: bool
+ RegularPowerSupply: bool
+ FunctionalPowerSupplyBackUp: bool
+ ContinuousWaterSupply: bool
+ AutomatedEquipment: bool
+ RegularServiceForEquipment: bool
+ ServiceAndMaintenanceRecords: bool
+ InventoryManagement: bool
+ WasteDisposalCompliant: bool
+ AccreditationYear: number
+ AccreditationBody: string
+ AccreditationScope: string
+ SLIPTA: bool
+ SLIPTARating: number
+ OtherQMSProgram: string
+ ASTQCProgram: bool
+ QCStaff: bool
+ ExternalQualityAssessment: bool
+ ReferenceStrains: bool
+ StrainSource: string
+ HasElectronicQCRecords: bool
+ HasPaperFormRecords: bool
+ FollowsASTSOPs: bool
+ HasContinuingEducationProgram: bool
+ CompetenceRecords: bool
+ SpecimenCollectionSOP: bool
+ PaperBasedIncomingSpecimenLog: bool
+ ElectronicBasedIncomingSpecimenLog: bool
+ OtherIncomingSpecimenLog: string
+ IdentifiedSpecimens: bool
+ BacterialCulturesPerYear: number
+ ASTsPerYear: number
+ CulturePositiveSpecimensPerYear: number
+ BacterialIdentificationMethods: many of
manual | automated | other (string)
+ ASTMethods: many of manual | automated |
other (string)
+ ASTStandards: none | CLSI | EUCAST |
Other (String)
+ ASTStorageMethods: paper | electronic
other (string) 
+ TRFCapturesDemographics: bool
+ TRFCapturesClinicalData
+ LinkedClinicalDiagnosis: bool
+ LinkedTreatment: bool
+ LinkedPatientOutcome: bool

**Comment by hdf1986** [comment]
TODO:
- [ ] Backend endpoints
- [ ] Frontend UI

**Comment by mverzilli** [comment]
Duplicate
